---
- hosts: jenkins_server
  tasks:
  
  - debug: var=ansible_facts['os_family']
  - name: Ensure java installed
    yum:
      name: java
      state: latest 
  - name: Download Jenkins.repo
    get_url:
      url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
    
  - name: Get Jenkins Key
    shell: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
      
  - name: Ensure jenkins Installed
    yum:
      name: jenkins
      state: latest
    notify:
    - restart jenkins
    
  - name: Ensure jenkins is running
    service:
      name: jenkins
      state: started
  - name: Enable Port 8080 in firwall
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
      immediate: yes
  handlers:
    - name: restart jenkins
      service:
        name: jenkins
        state: restarted

